/*Sistema para avanzar la ruleta de placas laser mediante pulsos al PAP

#include <furi.h>
#include <furi_hal_gpio.h>
#include <furi_hal_light.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <input/input.h>

/* generated by fbt from .png files in images folder */
#include <ruleta_laser_icons.h>

#define MOTOR_PULSE_COUNT     10U
#define MOTOR_PULSE_PERIOD_MS 3000U
#define MOTOR_PULSE_WIDTH_US  50000U

#define MOTOR_PIN_PORT   GPIOA
#define MOTOR_PIN_NUMBER LL_GPIO_PIN_7

typedef enum {
    StateConfirm,
    StateRunning,
} AppState;

typedef struct {
    const GpioPin* pin;
    bool status_active;
    AppState state;
    uint32_t current_pulse; // Guardamos el pulso actual para la barra de progreso
} MotorPulsesContext;

typedef enum {
    EventTypeInput,
    EventTypeTick,
} EventType;

typedef struct {
    EventType type;
    InputEvent input;
} AppEvent;

static void render_callback(Canvas* canvas, void* context) {
    MotorPulsesContext* ctx = context;
    canvas_clear(canvas);

    if(ctx->state == StateConfirm) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 2, 15, "¿Iniciar Ruleta?");

        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 2, 35, "Presiona OK para empezar");
        canvas_draw_str(canvas, 2, 50, "Presiona ATRAS para salir");
    } else if(ctx->state == StateRunning) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 2, 12, "Ruleta Laser");

        canvas_set_font(canvas, FontSecondary);
        if(ctx->status_active) {
            canvas_draw_str(canvas, 2, 26, "Enviando pulsos...");

            // --- DIBUJAR BARRA DE PROGRESO ---
            // Marco exterior de la barra: X=2, Y=32, Ancho=124, Alto=10
            canvas_draw_rframe(canvas, 2, 32, 124, 10, 2);
            // Calcular ancho dinámico basado en el progreso (máximo 120 píxeles internos)
            uint32_t bar_width = (ctx->current_pulse * 120) / MOTOR_PULSE_COUNT;
            if(bar_width > 120) bar_width = 120;
            // Rellenar la barra
            canvas_draw_box(canvas, 4, 34, bar_width, 6);
        } else {
            canvas_draw_str(canvas, 2, 30, "Esperando timer...");
        }

        canvas_draw_str(canvas, 2, 55, "Presiona ATRAS para parar");
    }
}

static void input_callback(InputEvent* input_event, void* queue_context) {
    furi_assert(queue_context);
    FuriMessageQueue* event_queue = queue_context;

    AppEvent event = {.type = EventTypeInput, .input = *input_event};
    furi_message_queue_put(event_queue, &event, FuriWaitForever);
}

static void motor_timer_callback(void* queue_context) {
    furi_assert(queue_context);
    FuriMessageQueue* event_queue = queue_context;

    AppEvent event = {.type = EventTypeTick};
    furi_message_queue_put(event_queue, &event, 0);
}

int32_t ruleta_laser_app(void* p) {
    UNUSED(p);

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(AppEvent));

    static const GpioPin motor_pin = {
        .port = MOTOR_PIN_PORT,
        .pin = MOTOR_PIN_NUMBER,
    };
    MotorPulsesContext context = {
        .pin = &motor_pin,
        .status_active = false,
        .state = StateConfirm,
        .current_pulse = 0,
    };

    furi_hal_gpio_init_simple(&motor_pin, GpioModeOutputPushPull);
    furi_hal_gpio_write(&motor_pin, false);

    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, render_callback, &context);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    FuriTimer* timer = furi_timer_alloc(motor_timer_callback, FuriTimerTypePeriodic, event_queue);
    if(timer == NULL) {
        FURI_LOG_E("ruleta_laser", "Failed to allocate timer");
        view_port_free(view_port);
        furi_record_close(RECORD_GUI);
        furi_message_queue_free(event_queue);
        return -1;
    }

    AppEvent event;
    bool running = true;
    bool timer_started = false;

    while(running) {
        FuriStatus status = furi_message_queue_get(event_queue, &event, FuriWaitForever);

        if(status == FuriStatusOk) {
            if(event.type == EventTypeInput) {
                if(event.input.key == InputKeyBack && event.input.type == InputTypeShort) {
                    FURI_LOG_I("ruleta_laser", "Exiting app");
                    running = false;
                }

                if(context.state == StateConfirm && event.input.key == InputKeyOk &&
                   event.input.type == InputTypeShort) {
                    FURI_LOG_I("ruleta_laser", "Starting motor pulse generator on PA7");
                    context.state = StateRunning;
                    furi_timer_start(timer, furi_ms_to_ticks(MOTOR_PULSE_PERIOD_MS));
                    timer_started = true;
                }
            } else if(event.type == EventTypeTick && context.state == StateRunning) {
                context.status_active = true;
                context.current_pulse = 0;
                view_port_update(view_port);

                // --- BUCLE DE PULSOS CONTROLADO ---
                for(uint32_t i = 0; i < MOTOR_PULSE_COUNT; i++) {
                    context.current_pulse = i + 1;
                    view_port_update(view_port); // Actualiza la barra en pantalla

                    // REVISIÓN DE BOTÓN DE EMERGENCIA INTERNA
                    AppEvent micro_event;
                    // Comprobamos si hay algo en la cola de inmediato (espera 0 ms)
                    if(furi_message_queue_get(event_queue, &micro_event, 0) == FuriStatusOk) {
                        if(micro_event.type == EventTypeInput &&
                           micro_event.input.key == InputKeyBack &&
                           micro_event.input.type == InputTypeShort) {
                            FURI_LOG_I("ruleta_laser", "Emergency stop triggered by user");
                            running = false;
                            break; // Rompe el bucle de pulsos inmediatamente
                        }
                    }

                    // 1. Pulso Alto
                    furi_hal_gpio_write(context.pin, true);
                    furi_hal_light_set(LightRed, 255);
                    furi_delay_us(MOTOR_PULSE_WIDTH_US);

                    // 2. Pulso Bajo
                    furi_hal_gpio_write(context.pin, false);
                    furi_hal_light_set(LightRed, 0);
                    furi_delay_us(MOTOR_PULSE_WIDTH_US);
                }

                FURI_LOG_I("ruleta_laser", "Sent %u pulses", MOTOR_PULSE_COUNT);
                context.status_active = false;
                context.current_pulse = 0;
                view_port_update(view_port);
            }
        }

        view_port_update(view_port);
    }

    if(timer_started) {
        furi_timer_stop(timer);
    }
    furi_timer_free(timer);

    furi_hal_gpio_write(&motor_pin, false);
    furi_hal_light_set(LightRed, 0);

    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(event_queue);

    return 0;
}
