/*Sistema para avanzar la ruleta de placas laser mediante pulsos al PAP con Menú Interactivo*/

#include <furi.h>
#include <furi_hal_gpio.h>
#include <furi_hal_light.h>
#include <gui/gui.h>
#include <gui/view_port.h>
#include <input/input.h>

/* generated by fbt from .png files in images folder */
#include <ruleta_laser_icons.h>

#define MOTOR_PIN_PORT   GPIOA
#define MOTOR_PIN_NUMBER LL_GPIO_PIN_7

typedef enum {
    StateConfig, // Nuevo estado: Configuración de parámetros
    StateConfirm,
    StateRunning,
} AppState;

// Índice de la opción seleccionada en el menú
typedef enum {
    MenuPulsosCount = 0,
    MenuPulsosPeriod,
    MenuPulsosWidth,
    Menu_MaxOptions
} MenuOption;

typedef struct {
    const GpioPin* pin;
    bool status_active;
    AppState state;
    uint32_t current_pulse;

    // --- VARIABLES DINÁMICAS (Configurables) ---
    uint32_t motor_pulse_count; // Cantidad de pulsos por grupo
    uint32_t motor_pulse_period_ms; // Intervalo entre grupos (Timer de Flipper)
    uint32_t motor_pulse_width_ms; // Intervalo entre pulsos (Ancho/espera del pulso en milisegundos)

    MenuOption selected_option; // Opción seleccionada en el menú
} MotorPulsesContext;

typedef enum {
    EventTypeInput,
    EventTypeTick,
} EventType;

typedef struct {
    EventType type;
    InputEvent input;
} AppEvent;

static void render_callback(Canvas* canvas, void* context) {
    MotorPulsesContext* ctx = context;
    canvas_clear(canvas);

    // --- PANTALLA DE CONFIGURACIÓN ---
    if(ctx->state == StateConfig) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 2, 12, "Configuracion Motor");

        canvas_set_font(canvas, FontSecondary);

        // Formatear cadenas para mostrar los valores actuales
        char buf[32];

        // Opción 1: Cantidad de pulsos
        snprintf(
            buf,
            sizeof(buf),
            "%s Pulsos: %lu",
            (ctx->selected_option == MenuPulsosCount) ? ">" : " ",
            ctx->motor_pulse_count);
        canvas_draw_str(canvas, 4, 26, buf);

        // Opción 2: Intervalo entre pulsos (Ancho del paso)
        snprintf(
            buf,
            sizeof(buf),
            "%s Int. Pulso: %lu ms",
            (ctx->selected_option == MenuPulsosPeriod) ? ">" : " ",
            ctx->motor_pulse_width_ms);
        canvas_draw_str(canvas, 4, 38, buf);

        // Opción 3: Intervalo entre grupos (Frecuencia del timer)
        snprintf(
            buf,
            sizeof(buf),
            "%s Int. Grupo: %lu ms",
            (ctx->selected_option == MenuPulsosWidth) ? ">" : " ",
            ctx->motor_pulse_period_ms);
        canvas_draw_str(canvas, 4, 50, buf);

        canvas_draw_str(canvas, 2, 62, "[OK] Confirmar  [< >] Ajustar");
    }
    // --- PANTALLA DE CONFIRMACIÓN ---
    else if(ctx->state == StateConfirm) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 2, 15, "¿Iniciar Ruleta?");

        canvas_set_font(canvas, FontSecondary);
        canvas_draw_str(canvas, 2, 35, "Presiona OK para empezar");
        canvas_draw_str(canvas, 2, 50, "Presiona ATRAS para volver");
    }
    // --- PANTALLA EN EJECUCIÓN ---
    else if(ctx->state == StateRunning) {
        canvas_set_font(canvas, FontPrimary);
        canvas_draw_str(canvas, 2, 12, "Ruleta Laser");

        canvas_set_font(canvas, FontSecondary);
        if(ctx->status_active) {
            canvas_draw_str(canvas, 2, 26, "Enviando pulsos...");

            // --- DIBUJAR BARRA DE PROGRESO ---
            canvas_draw_rframe(canvas, 2, 32, 124, 10, 2);
            uint32_t bar_width = (ctx->current_pulse * 120) / ctx->motor_pulse_count;
            if(bar_width > 120) bar_width = 120;
            canvas_draw_box(canvas, 4, 34, bar_width, 6);
        } else {
            canvas_draw_str(canvas, 2, 30, "Esperando timer...");
        }

        canvas_draw_str(canvas, 2, 55, "Presiona ATRAS para parar");
    }
}

static void input_callback(InputEvent* input_event, void* queue_context) {
    furi_assert(queue_context);
    FuriMessageQueue* event_queue = queue_context;

    AppEvent event = {.type = EventTypeInput, .input = *input_event};
    furi_message_queue_put(event_queue, &event, FuriWaitForever);
}

static void motor_timer_callback(void* queue_context) {
    furi_assert(queue_context);
    FuriMessageQueue* event_queue = queue_context;

    AppEvent event = {.type = EventTypeTick};
    furi_message_queue_put(event_queue, &event, 0);
}

int32_t ruleta_laser_app(void* p) {
    UNUSED(p);

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(AppEvent));

    static const GpioPin motor_pin = {
        .port = MOTOR_PIN_PORT,
        .pin = MOTOR_PIN_NUMBER,
    };

    // Inicializamos el contexto con valores por defecto mutables
    MotorPulsesContext context = {
        .pin = &motor_pin,
        .status_active = false,
        .state = StateConfig, // Arranca en el menú de configuración
        .current_pulse = 0,
        .motor_pulse_count = 10, // Por defecto 10 pulsos
        .motor_pulse_width_ms =
            50, // Por defecto 50ms en alto y 50ms en bajo (anteriormente 50000us)
        .motor_pulse_period_ms = 3000, // Por defecto 3 segundos entre grupos
        .selected_option = MenuPulsosCount,
    };

    furi_hal_gpio_init_simple(&motor_pin, GpioModeOutputPushPull);
    furi_hal_gpio_write(&motor_pin, false);

    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, render_callback, &context);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    FuriTimer* timer = furi_timer_alloc(motor_timer_callback, FuriTimerTypePeriodic, event_queue);
    if(timer == NULL) {
        FURI_LOG_E("ruleta_laser", "Failed to allocate timer");
        view_port_free(view_port);
        furi_record_close(RECORD_GUI);
        furi_message_queue_free(event_queue);
        return -1;
    }

    AppEvent event;
    bool running = true;
    bool timer_started = false;

    while(running) {
        FuriStatus status = furi_message_queue_get(event_queue, &event, FuriWaitForever);

        if(status == FuriStatusOk) {
            if(event.type == EventTypeInput) {
                // MAVENGACIÓN GENERAL DEL BOTÓN ATRÁS
                if(event.input.key == InputKeyBack && event.input.type == InputTypeShort) {
                    if(context.state == StateConfig) {
                        FURI_LOG_I("ruleta_laser", "Exiting app from config");
                        running = false;
                    } else if(context.state == StateConfirm) {
                        context.state = StateConfig; // Regresar a configurar
                    } else if(context.state == StateRunning) {
                        FURI_LOG_I("ruleta_laser", "Stopping execution");
                        if(timer_started) {
                            furi_timer_stop(timer);
                            timer_started = false;
                        }
                        context.state = StateConfig; // Parar y volver al menú
                    }
                }

                // LÓGICA DE INTERACCIÓN EN ESTADO DE CONFIGURACIÓN
                else if(context.state == StateConfig && event.input.type == InputTypeShort) {
                    if(event.input.key == InputKeyUp) {
                        if(context.selected_option > 0) context.selected_option--;
                    } else if(event.input.key == InputKeyDown) {
                        if(context.selected_option < Menu_MaxOptions - 1)
                            context.selected_option++;
                    } else if(event.input.key == InputKeyRight) {
                        // Incrementar valores según la opción
                        if(context.selected_option == MenuPulsosCount)
                            context.motor_pulse_count += 1;
                        else if(context.selected_option == MenuPulsosPeriod)
                            context.motor_pulse_width_ms += 5;
                        else if(context.selected_option == MenuPulsosWidth)
                            context.motor_pulse_period_ms += 250;
                    } else if(event.input.key == InputKeyLeft) {
                        // Decrementar valores (evitando que bajen de límites seguros)
                        if(context.selected_option == MenuPulsosCount &&
                           context.motor_pulse_count > 1)
                            context.motor_pulse_count -= 1;
                        else if(
                            context.selected_option == MenuPulsosPeriod &&
                            context.motor_pulse_width_ms > 5)
                            context.motor_pulse_width_ms -= 5;
                        else if(
                            context.selected_option == MenuPulsosWidth &&
                            context.motor_pulse_period_ms > 250)
                            context.motor_pulse_period_ms -= 250;
                    } else if(event.input.key == InputKeyOk) {
                        context.state = StateConfirm; // Pasar a confirmación
                    }
                }

                // LÓGICA EN ESTADO DE CONFIRMACIÓN
                else if(
                    context.state == StateConfirm && event.input.key == InputKeyOk &&
                    event.input.type == InputTypeShort) {
                    FURI_LOG_I("ruleta_laser", "Starting motor pulse generator on PA7");
                    context.state = StateRunning;
                    // Se inicia el timer usando el periodo configurado dinámicamente
                    furi_timer_start(timer, furi_ms_to_ticks(context.motor_pulse_period_ms));
                    timer_started = true;
                }

            } else if(event.type == EventTypeTick && context.state == StateRunning) {
                context.status_active = true;
                context.current_pulse = 0;
                view_port_update(view_port);

                // --- BUCLE DE PULSOS CONTROLADO CON VARIABLES DEL MENÚ ---
                for(uint32_t i = 0; i < context.motor_pulse_count; i++) {
                    context.current_pulse = i + 1;
                    view_port_update(view_port);

                    // REVISIÓN DE BOTÓN DE EMERGENCIA INTERNA
                    AppEvent micro_event;
                    if(furi_message_queue_get(event_queue, &micro_event, 0) == FuriStatusOk) {
                        if(micro_event.type == EventTypeInput &&
                           micro_event.input.key == InputKeyBack &&
                           micro_event.input.type == InputTypeShort) {
                            FURI_LOG_I("ruleta_laser", "Emergency stop triggered by user");
                            context.state = StateConfig;
                            if(timer_started) {
                                furi_timer_stop(timer);
                                timer_started = false;
                            }
                            break;
                        }
                    }

                    // 1. Pulso Alto
                    furi_hal_gpio_write(context.pin, true);
                    furi_hal_light_set(LightRed, 255);
                    furi_delay_ms(context.motor_pulse_width_ms);

                    // 2. Pulso Bajo
                    furi_hal_gpio_write(context.pin, false);
                    furi_hal_light_set(LightRed, 0);
                    furi_delay_ms(context.motor_pulse_width_ms);
                }

                FURI_LOG_I("ruleta_laser", "Sent %lu pulses", context.motor_pulse_count);
                context.status_active = false;
                context.current_pulse = 0;
                view_port_update(view_port);
            }
        }

        view_port_update(view_port);
    }

    if(timer_started) {
        furi_timer_stop(timer);
    }
    furi_timer_free(timer);

    furi_hal_gpio_write(&motor_pin, false);
    furi_hal_light_set(LightRed, 0);

    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_record_close(RECORD_GUI);
    furi_message_queue_free(event_queue);

    return 0;
}
